# Generated by Django 5.1.6 on 2025-02-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='component',
            new_name='components',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='library',
            new_name='libraries',
        ),
    ]
