# Generated by Django 5.1.6 on 2025-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='history_window_size',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
