# Generated by Django 5.1.6 on 2025-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_messageembedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="board",
        ),
        migrations.AddField(
            model_name="project",
            name="board_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name="project",
            name="components",
        ),
        migrations.AlterField(
            model_name="project",
            name="history_window_size",
            field=models.IntegerField(default=10),
        ),
        migrations.RemoveField(
            model_name="project",
            name="libraries",
        ),
        migrations.AddField(
            model_name="project",
            name="components",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="libraries",
            field=models.TextField(blank=True),
        ),
    ]
