# Generated by Django 5.1.6 on 2025-02-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.boardtype",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="components_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="libraries_text",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="components",
        ),
        migrations.RemoveField(
            model_name="project",
            name="libraries",
        ),
        migrations.AddField(
            model_name="project",
            name="components",
            field=models.ManyToManyField(blank=True, to="chat.component"),
        ),
        migrations.AddField(
            model_name="project",
            name="libraries",
            field=models.ManyToManyField(blank=True, to="chat.library"),
        ),
    ]
