# Generated by Django 5.1.6 on 2025-02-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_project_board_project_components_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="board",
        ),
        migrations.RemoveField(
            model_name="project",
            name="components",
        ),
        migrations.RemoveField(
            model_name="project",
            name="libraries",
        ),
    ]
