# Generated by Django 5.1.6 on 2025-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_userprofile_delete_boardtype_delete_component_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="query_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="summary_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_query_model",
            field=models.CharField(
                choices=[
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                ],
                default="gpt-3.5-turbo",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_summary_model",
            field=models.CharField(
                choices=[
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                ],
                default="gpt-3.5-turbo",
                max_length=50,
            ),
        ),
    ]
