# Generated by Django 5.1.6 on 2025-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_update_project_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_users_count", models.IntegerField(default=0)),
                ("max_beta_users", models.IntegerField(default=25)),
                ("beta_registration_open", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
