# Generated by Django 5.1.6 on 2025-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='max_beta_users',
            field=models.IntegerField(default=2),
        ),
    ]
