# Generated by Django 5.1.6 on 2025-03-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_sitesettings_max_beta_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="max_tokens",
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="max_beta_users",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tokens_remaining",
            field=models.IntegerField(default=100000),
        ),
    ]
