# Generated by Django 5.1.7 on 2025-04-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_project_board_fqbn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="project",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                default="openai",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="default_query_model",
            field=models.CharField(
                choices=[
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("claude-3-opus-20240229", "Claude 3 Opus"),
                    ("claude-3-sonnet-20240229", "Claude 3 Sonnet"),
                    ("claude-3-haiku-20240307", "Claude 3 Haiku"),
                    ("claude-3-5-sonnet-20240620", "Claude 3.5 Sonnet"),
                ],
                default="gpt-3.5-turbo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="default_summary_model",
            field=models.CharField(
                choices=[
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("claude-3-opus-20240229", "Claude 3 Opus"),
                    ("claude-3-sonnet-20240229", "Claude 3 Sonnet"),
                    ("claude-3-haiku-20240307", "Claude 3 Haiku"),
                    ("claude-3-5-sonnet-20240620", "Claude 3.5 Sonnet"),
                ],
                default="gpt-3.5-turbo",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Mode"),
                            ("widget", "Widget Mode"),
                            ("library", "Learn a Library Mode"),
                            ("topic", "Learn a Topic Mode"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        blank=True,
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("board_fqbn", models.CharField(blank=True, max_length=100, null=True)),
                ("board_type", models.CharField(blank=True, max_length=100)),
                ("components_text", models.TextField(blank=True)),
                ("libraries_text", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("history_window_size", models.IntegerField(default=10)),
                (
                    "query_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("gpt-4", "GPT-4"),
                            ("gpt-4o", "GPT-4o"),
                            ("gpt-4o-mini", "GPT-4o Mini"),
                            ("claude-3-opus-20240229", "Claude 3 Opus"),
                            ("claude-3-sonnet-20240229", "Claude 3 Sonnet"),
                            ("claude-3-haiku-20240307", "Claude 3 Haiku"),
                            ("claude-3-5-sonnet-20240620", "Claude 3.5 Sonnet"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "summary_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("gpt-4", "GPT-4"),
                            ("gpt-4o", "GPT-4o"),
                            ("gpt-4o-mini", "GPT-4o Mini"),
                            ("claude-3-opus-20240229", "Claude 3 Opus"),
                            ("claude-3-sonnet-20240229", "Claude 3 Sonnet"),
                            ("claude-3-haiku-20240307", "Claude 3 Haiku"),
                            ("claude-3-5-sonnet-20240620", "Claude 3.5 Sonnet"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("target_platform", models.CharField(blank=True, max_length=100)),
                (
                    "complexity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple", "Simple"),
                            ("intermediate", "Intermediate"),
                            ("complex", "Complex"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("library_name", models.CharField(blank=True, max_length=100)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("topic_name", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.session",
            ),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
