# Generated by Django 5.2.3 on 2025-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bb_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
