# Generated by Django 5.2.3 on 2025-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bb_app", "0002_message_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("user", "User"),
                    ("assistant", "Assistant"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
