# Generated by Django 5.2.3 on 2025-09-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bb_app", "0003_message_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="response_id",
            field=models.TextField(default=""),
        ),
    ]
